### ISSUE TITLE
Problems with blueprint

### ISSUE THREAD

**Issue by Antoine-dSG** [Antoine-dSG/frieze_patterns#1]
There are a couple of problems with the website & and blueprint:
- The address https://antoine-dsg.github.io/frieze_patterns/ returns a 404. I am not quite sure how to fix it
- The \lean command doesn't work (if such a command is used in the Latex, github returns an error during the building stage)

**Comment by skylee03** [comment]
For the first problem, I think you should [configure the GitHub Pages in the settings](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

**Comment by skylee03** [comment]
The directory structure of the artifact is as follows:

```
artifact.tar
├─ blueprint/
├─ docs/
├─ blueprint.pdf
```

That is, to check the docs, we should visit https://antoine-dsg.github.io/frieze_patterns/docs/.

There is no `index.html` inside `artifact.tar`, so the address https://antoine-dsg.github.io/frieze_patterns/ returns a 404. To fix it, we can put the `index.html` inside `artifact.tar` (i.e., inside the folder `docs/`). Here is the example:
- https://skylee03.github.io/frieze_patterns/
- https://github.com/skylee03/frieze_patterns

I am not sure if this is what you were looking for, but I hope this helps.

**Comment by Antoine-dSG** [comment]
This looks like what I was looking for; thank you !

**Comment by skylee03** [comment]
I think we should also remove `mkdir docs` from the workflow, since this directory already exists.
